# config_hdo.ini

[DIRECTORIES]

GRAFdatadir_conus_old = /storage2/library/archive/grid/hdo-graflr_conus/
GRAFdatadir_conus_new = /storage2/library/archive/grid/hdo-graf_conus/
probs_directory = /data/resnet/GRAFprobs/
MRMS_directory = /data/resnet_data/MRMS/

[PARAMETERS]

quality_threshold = 0.6




