# config_hdo.ini

[DIRECTORIES]

GRAFdatadir_conus_old = /data/resnet_data/GRAF/hdo-graflr_conus/
GRAFdatadir_conus_new = /data/resnet_data/GRAF/hdo-graf_conus/
probs_directory = /data/resnet_data/GRAFprobs/
MRMS_directory = /data/resnet_data/MRMS/

[PARAMETERS]

quality_threshold = 0.6




